#VARIAVEIS

@baseUrl= http://localhost:3333

#HEALTH check

GET {{baseUrl}}/health

###
#GET ROOMS
# @name getRooms
GET {{baseUrl}}/rooms

###

#create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de Teste",
    "description": "Essa é uma sala de Teste"
}
###

@roomId ={{createRoom.response.body.$.roomId}}


###
#Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

#create Question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "Qual o conceito de X dentro de Y?"
}